[General]
# Logging level
# VERBOSE = 0
# DEBUG = 1
# INFO = 2
# WARNING = 3
# ERROR = 4
# FATAL = 5
logLevel = 1

[MaterialMapJsonConverter]
# Material mapping options
processSensitives = true
processApproaches = true
processRepresenting = true
processBoundaries = true
processVolumes = true
processDenseVolumes = false
processNonMaterial = false

[JsonMaterialDecorator]
# Material map path
materialPath = """
/home/romanurmanov/work/E320/E320Prototype/\
E320Prototype_material/\
Uniform_DirectZ_Tracker_PDCWindow_256x128_1e6/material.json\
"""

[Geometry]
# Local alignment shifts [um]
localShiftY10 = 0
localShiftY12 = 0
localShiftY14 = 0
localShiftY16 = 0
localShiftY18 = 0

localShiftZ10 = 0
localShiftZ12 = 0
localShiftZ14 = 0
localShiftZ16 = 0
localShiftZ18 = 0

# Local alignment angles [mrad]
localAngleZ10 = 0
localAngleZ12 = 0
localAngleZ14 = 0
localAngleZ16 = 0
localAngleZ18 = 0

# Global alignment shifts [mm]
globalShiftY = 0
globalShiftZ = 0

# Global alignment angles [mrad]
globalAngleZ = 0

# Use material decorator for the 
# material description
materialDecorator = true

[Sequencer]
# Event skip
skip = 0

# Number of events
events = 1000

# Number of threads
numThreads = 1

# FPE tracking
trackFpes = false

[E320RootTrackReader]
# Flag to require a specific EPICS parity
requireEpicsParity = true

# Required EPICS parity
# 0 = even
# 1 = odd
requiredEpicsParity = 0


minXCount = 5
maxXCount = 20

# Cut on the tracks predicted chi2
minPredictedChi2 = 0
maxPredictedChi2 = 3000

# Cut on the tracks filtered chi2
minFilteredChi2 = 0
maxFilteredChi2 = 3000

# Cut on the tracks smoothed chi2
minSmoothedChi2 = 0
maxSmoothedChi2 = 40

# Cut on the tracks vertex long coordinate [mm]
minVertexEstLong = -20
maxVertexEstLong = 20

# Cut on the tracks vertex short coordinate [mm]
minVertexEstShort = -20
maxVertexEstShort = 20

# Cut on the tracks energy [GeV]
minAbsMomentumEst = 1
maxAbsMomentumEst = 10

# Directory with the track data
inDirTracks = """
/home/romanurmanov/work/E320/E320Prototype/\
E320Prototype_analysis/data/alignment/\
local_2026_data/ht_test/sig/filtered\
"""

# Input tree name
treeName = "fitted-tracks"

# WhiteBoard name of the output source links
outputSourceLinks = "SourceLinks"

# WhiteBoard name of the output guess seeds
outputSeedsGuess = "SeedsGuess"

# WhiteBoard name of the output guess track parameters
outputTrackParametersGuess = "TrackParametersGuess"

# WhiteBoard name of the output estimated seeds
outputSeedsEst = "SeedsEst"

# WhiteBoard name of the output estimated track parameters
outputTrackParametersEst = "TrackParametersEst"

# WhiteBoard name of the output magnetic field parameters
outputMagneticFieldParameters = "MagFieldPars"

# WhiteBoard name of the output event meta data
outputEventMetaData = "EventMetaData"

# Flag to merge all tracks into a single event
mergeIntoOneEvent = true

# Flag to account for backwards propagation
backwards = false

# Cut on the residuals in the chips
[[E320RootTrackReader.smoothedResidualsRange]]
geoId = 16
# minSmoothedResidualX = 0.005
# maxSmoothedResidualX = 0.05
# minSmoothedResidualY = -0.065
# maxSmoothedResidualY = -0.005

minSmoothedResidualX = -10
maxSmoothedResidualX = 10
minSmoothedResidualY = -10
maxSmoothedResidualY = 10

[E320TrackParametersEstimator]
# Number of GX2 fit iterations
nIterations = 2

# Max GX2 chi2 cut
maxChi2 = 1e9
# maxChi2 = 100

# Propagation direction
# forward = 0
# backward = 1
propDirection = 0

[LocalAlignmentParametersSolverSVD]
# Cut on the relative magnitude between 
# a given singular value and the largest
# singular value of the alignment fit Hessian
maxSingularValueTol = 1e-5

# Cut on the relative magnitude between 
# a given singular value and the next largest
# singular value that overrides the 
# maxSingularValueTol cut
singularValueGapTol = 9e-1

[ActsAlignmentFunction]
# Cut on the number of the KF steps
maxKFSteps = 100000

# Chi2/ndf triggering the fit stop
chi2ONdfCutOff = 1e-16

# Chi2/ndf average detla triggering the fit stop
deltaChi2ONdfCutOffDelta = 1e-5

# Number of steps for averaging chi2/ndf  
# detla triggering the fit stop
deltaChi2ONdfCutOffNSteps = 10

# Cut on the maximum number of fit iterations
maxAlignmentFitNumIt = 200

[AlignmentAlgorithm]
# WhiteBoard name of the input source links
inputSourceLinks = "SourceLinks"

# WhiteBoard name of the input track candidates
inputTrackCandidates = "SeedsGuess"

# WhiteBoard name of the input track parameters
inputTrackParameters = "TrackParametersGuess"

# WhiteBoard name of the input magnetic field parameters
inputMagneticFieldParameters = "MagFieldPars"

# WhiteBoard name of the output alignment parameters
outputAlignmentParameters = "AlignmentParameters"

# WhiteBoard name of the output updated track parameters
outputTrackParameters = "UpdatedTrackParameters"

[KFTrackFittingAlgorithm]
# WhiteBoard name of the input track candidates
inputTrackCandidates = "SeedsGuess"

# WhiteBoard name of the input track parameters
inputTrackParameters = "UpdatedTrackParameters"

# WhiteBoard name of the input source links
inputSourceLinks = "SourceLinks"

# WhiteBoard name of the output track container
outputTrackContainer = "TrackContainer"

# WhiteBoard name of the output tracks
outputTracks = "Tracks"

# Cut on the maximum number of KF steps
maxSteps = 100000

[E320RootTrackWriter]
# WhiteBoard name of the input track container
inputTrackContainer = "TrackContainer"

# WhiteBoard name of the input tracks
inputTracks = "Tracks"

# WhiteBoard name of the input track parameters
inputTrackParametersGuesses = "UpdatedTrackParameters"

# WhiteBoard name of the input event meta data
inputEventMetaData = "EventMetaData"

# Output tree name
treeName = "fitted-tracks"

# Output file path
filePath = """
/home/romanurmanov/work/E320/E320Prototype/E320Prototype_analysis/\
data/\
fitted-tracks.root\
"""

[AlignmentParametersWriter]
# WhiteBoard name of the input alignment parameters
inputAlignmentResults = "AlignmentParameters"

# Output tree name
treeName = "alignment-parameters"

# Output file path
filePath = """
/home/romanurmanov/work/E320/E320Prototype/E320Prototype_analysis/\
data/\
alignment-parameters.root\
"""
