[General]
# Logging level
# VERBOSE = 0
# DEBUG = 1
# INFO = 2
# WARNING = 3
# ERROR = 4
# FATAL = 5
logLevel = 2

[MaterialMapJsonConverter]
# Material mapping options
processSensitives = true
processApproaches = true
processRepresenting = true
processBoundaries = true
processVolumes = true
processDenseVolumes = false
processNonMaterial = false

[JsonMaterialDecorator]
# Material map path
materialPath = """
/home/romanurmanov/work/E320/E320Prototype/\
E320Prototype_material/\
Uniform_DirectZ_Tracker_PDCWindow_256x128_1e6/material.json\
"""

[Geometry]
# # Global alignment shifts [mm]
# globalShiftY = 0
# globalShiftZ = 0
# 
# # Global alignment angles [mrad]
# globalAngleZ = 0

# Local alignment shifts [um]
localShiftY10 = 0
localShiftY12 = 0
localShiftY14 = 0
localShiftY16 = 0
localShiftY18 = 0

localShiftZ10 = 0
localShiftZ12 = 0
localShiftZ14 = 0
localShiftZ16 = 0
localShiftZ18 = 0

# Local alignment angles [mrad]
localAngleZ10 = 0
localAngleZ12 = 0
localAngleZ14 = 0
localAngleZ16 = 0
localAngleZ18 = 0

# Global alignment shifts [mm]
globalShiftY = -2.5
globalShiftZ = -4.5

# Global alignment angles [mrad]
globalAngleZ = -2 

# # Local alignment shifts [um]
# localShiftY10 = 87.1378
# localShiftY12 = -42.9543
# localShiftY14 = -85.2652
# localShiftY16 = -49.1208
# localShiftY18 = 90.2019
# 
# localShiftZ10 = 79.183
# localShiftZ12 = -51.5106
# localShiftZ14 = -54.0668
# localShiftZ16 = -54.0977
# localShiftZ18 = 80.4914
# 
# # Local alignment angles [mrad]
# localAngleZ10 = -0.778647
# localAngleZ12 = 1.0279
# localAngleZ14 = -3.05136
# localAngleZ16 = -0.461109
# localAngleZ18 = -3.25102

# Noam's alignment
# localShiftY10 = 0
# localShiftY12 = 39.3
# localShiftY14 = -53.9
# localShiftY16 = -64.2
# localShiftY18 = 27.5
# 
# localShiftZ10 = 0
# localShiftZ12 = 23.5
# localShiftZ14 = -28.8
# localShiftZ16 = -64.9
# localShiftZ18 = 24.6
# 
# # Local alignment angles [mrad]
# localAngleZ10 = 0
# localAngleZ12 = -1.8
# localAngleZ14 = 1.6
# localAngleZ16 = -1.5
# localAngleZ18 = 0.5

# Use material decorator for the 
# material description
materialDecorator = true

[Sequencer]
# Event skip
skip = 0

# Number of events
events = 10000000

# Number of threads
numThreads = 1

# FPE tracking
trackFpes = false

[DummyReader]
# WhiteBoard name of the output sim measurements
outputSourceLinks = "SimMeasurements"

# WhiteBoard name of the output sim clusters
outputSimClusters = "SimClusters"

# WhiteBoard name of the output sim measurement indices
outputSourceLinkIndices = "SimMeasurementIndices"

# Number of event to generate
nEvents = 10000

[GaussianVertexGenerator]
# Vertex resolution [um]
vertexResolution = 30

[SphericalMomentumGenerator]
# Absolute momentum range [GeV]
# minAbsoluteMomentum = 3.0
# maxAbsoluteMomentum = 4.0

minAbsoluteMomentum = 1.5
maxAbsoluteMomentum = 2.5

# Phi angle range [mrad]
minPhi = -1
maxPhi = 1

# Theta angle range with respect to M_PI_2 [mrad]
minTheta = -1
maxTheta = 1

[TrackHitDigitizer]
# Gaussian hit smearing resolution
# for constraint surfaces [um]
constraintSurfaceResolutionX = 200
constraintSurfaceResolutionY = 200

# Gaussian hit smearing resolution
# for tracking detector surfaces [um]
trackingSurfaceResolutionX = 5
trackingSurfaceResolutionY = 5

[[ClusterSizeBasedDigitizer]]
# Size of the simulated cluster [N pix]
clusterSize = 1

# Sampling probability of the size
samplingProb = 0.168115

# Hit X resolution in local surface frame [um]
resolutionX = 3.33208

# Hit Y resolution in local surface frame [um]
resolutionY = 3.95262

[[ClusterSizeBasedDigitizer]]
# Size of the simulated cluster [N pix]
clusterSize = 2

# Sampling probability of the size
samplingProb = 0.284536

# Hit X resolution in local surface frame [um]
resolutionX = 4.73498

# Hit Y resolution in local surface frame [um]
resolutionY = 4.44654

[[ClusterSizeBasedDigitizer]]
# Size of the simulated cluster [N pix]
clusterSize = 3

# Sampling probability of the size
samplingProb = 0.217946

# Hit X resolution in local surface frame [um]
resolutionX = 4.31227

# Hit Y resolution in local surface frame [um]
resolutionY = 4.17356

[[ClusterSizeBasedDigitizer]]
# Size of the simulated cluster [N pix]
clusterSize = 4

# Sampling probability of the size
samplingProb = 0.329402

# Hit X resolution in local surface frame [um]
resolutionX = 4.90848

# Hit Y resolution in local surface frame [um]
resolutionY = 5.09384

[TrackAngleDigitizer]
# Gaussian angle smearing resolution
# for constraint surfaces [mrad]
constraintSurfaceResolutionPhi = 1
constraintSurfaceResolutionTheta = 1

[SigMeasurementsEmbeddingAlgorithm]
# WhiteBoard name of the input sim measurements
inputSourceLinks = "SimMeasurements"

# WhiteBoard name of the input sim clusters
inputSimClusters = "SimClusters"

# WhiteBoard name of the input sim measurement indices
inputSourceLinkIndices = "SimMeasurementIndices"

# WhiteBoard name of the output measurements
outputSourceLinks = "Measurements"

# WhiteBoard name of the output clusters
outputSimClusters = "Clusters"

# WhiteBoard name of the output measurement indices
outputSourceLinkIndices = "MeasurementIndices"

# Number of measurements to generate
nMeasurements = 1

[UniformBackgroundCreator]
# Measurement resolution in local X axis
resolutionX = 5

# Measurement resolution in local Y axis
resolutionY = 5

# Number of generated measurements per surface
nMeasurementsPerSurface = 20

[BkgMeasurementsEmbeddingAlgorithm]
# WhiteBoard name of the input sim measurements
inputSourceLinks = "Measurements1"

# WhiteBoard name of the input sim clusters
inputSimClusters = "Clusters1"

# WhiteBoard name of the input sim measurement indices
inputSourceLinkIndices = "MeasurementIndices1"

# WhiteBoard name of the output measurements
outputSourceLinks = "Measurements"

# WhiteBoard name of the output clusters
outputSimClusters = "Clusters"

# WhiteBoard name of the output measurement indices
outputSourceLinkIndices = "MeasurementIndices"

# Number of measurements to generate
nMeasurements = 1

[E320RootSimClusterWriter]
# WhiteBoard name of the input clusters
inputClusters = "Clusters"

# Output tree name
treeName = "clusters"

# Output file path
filePath = """
/home/romanurmanov/work/E320/E320Prototype/\
E320Prototype_dataInRootFormat/sim/\
clusters.root\
"""

[E320MagneticFieldWriter]
# Output tree name
treeName = "magnets"

# Output file path
filePath = """
/home/romanurmanov/work/E320/E320Prototype/\
E320Prototype_dataInRootFormat/sim/\
magnets.root\
"""
