[General]
# Logging level
# VERBOSE = 0
# DEBUG = 1
# INFO = 2
# WARNING = 3
# ERROR = 4
# FATAL = 5
logLevel = 2

[MaterialMapJsonConverter]
# Material mapping options
processSensitives = true
processApproaches = true
processRepresenting = true
processBoundaries = true
processVolumes = true
processDenseVolumes = false
processNonMaterial = false

[JsonMaterialDecorator]
# Material map path
materialPath = """
/home/romanurmanov/work/E320/E320Prototype/\
E320Prototype_material/\
Uniform_DirectZ_Tracker_PDCWindow_256x128_1e6/material.json\
"""

[Geometry]
# # Global alignment shifts [mm]
# globalShiftY = 0
# globalShiftZ = 0
# 
# # Global alignment angles [mrad]
# globalAngleZ = 0

# # Local alignment shifts [um]
# localShiftY10 = 0
# localShiftY12 = 0
# localShiftY14 = 0
# localShiftY16 = 0
# localShiftY18 = 0
# 
# localShiftZ10 = 0
# localShiftZ12 = 0
# localShiftZ14 = 0
# localShiftZ16 = 0
# localShiftZ18 = 0
# 
# # Local alignment angles [mrad]
# localAngleZ10 = 0
# localAngleZ12 = 0
# localAngleZ14 = 0
# localAngleZ16 = 0
# localAngleZ18 = 0

# Global alignment shifts [mm]
globalShiftY = -2.5
globalShiftZ = -4.5

# Global alignment angles [mrad]
globalAngleZ = -2

# Local alignment shifts [um]
localShiftY10 = 87.1026
localShiftY12 = -42.9392
localShiftY14 = -85.2415
localShiftY16 = -49.0838
localShiftY18 = 90.1621

localShiftZ10 = 79.0526
localShiftZ12 = -51.4421
localShiftZ14 = -53.9096
localShiftZ16 = -54.074
localShiftZ18 = 80.3726

# Local alignment angles [mrad]
localAngleZ10 = -2.16419
localAngleZ12 = -0.314002
localAngleZ14 = -4.34635
localAngleZ16 = -1.71339
localAngleZ18 = -4.45922

# # Local alignment shifts [um]
# localShiftY10 = 18.3344
# localShiftY12 = 25.0112
# localShiftY14 = -50.0314
# localShiftY16 = -48.2874
# localShiftY18 = 54.9776
# 
# localShiftZ10 = 14.4245
# localShiftZ12 = 12.6156
# localShiftZ14 = -21.0681
# localShiftZ16 = -53.4449
# localShiftZ18 = 47.4642
# 
# # Local alignment angles [mrad]
# localAngleZ10 = 1.47486
# localAngleZ12 = 1.36707
# localAngleZ14 = -2.68634
# localAngleZ16 = -0.0745296
# localAngleZ18 = -2.83556

# Use material decorator for the 
# material description
materialDecorator = true

[Sequencer]
# Event skip
skip = 0

# Number of events
events = 100000

# Number of threads
numThreads = 1

# FPE tracking
trackFpes = false

[DummyReader]
# WhiteBoard name of the output sim measurements
outputSourceLinks = "SimMeasurements"

# WhiteBoard name of the output sim clusters
outputSimClusters = "SimClusters"

# WhiteBoard name of the output sim measurement indices
outputSourceLinkIndices = "SimMeasurementIndices"

# Number of event to generate
nEvents = 1000000

[GaussianVertexGenerator]
# Vertex resolution [um]
vertexResolution = 30

[SphericalMomentumGenerator]
# Absolute momentum range [GeV]
# minAbsoluteMomentum = 3.0
# maxAbsoluteMomentum = 4.0

minAbsoluteMomentum = 1.5
maxAbsoluteMomentum = 2.5

# Phi angle range [mrad]
minPhi = -1
maxPhi = 1

# Theta angle range with respect to M_PI_2 [mrad]
minTheta = -1
maxTheta = 1

[TrackHitDigitizer]
# Gaussian hit smearing resolution
# for constraint surfaces [um]
constraintSurfaceResolutionX = 200
constraintSurfaceResolutionY = 200

# Gaussian hit smearing resolution
# for tracking detector surfaces [um]
trackingSurfaceResolutionX = 5
trackingSurfaceResolutionY = 5

[[ClusterSizeBasedDigitizer]]
# Size of the simulated cluster [N pix]
clusterSize = 1

# Sampling probability of the size
samplingProb = 0.168115

# Hit X resolution in local surface frame [um]
resolutionX = 3.33208

# Hit Y resolution in local surface frame [um]
resolutionY = 3.95262

[[ClusterSizeBasedDigitizer]]
# Size of the simulated cluster [N pix]
clusterSize = 2

# Sampling probability of the size
samplingProb = 0.284536

# Hit X resolution in local surface frame [um]
resolutionX = 4.73498

# Hit Y resolution in local surface frame [um]
resolutionY = 4.44654

[[ClusterSizeBasedDigitizer]]
# Size of the simulated cluster [N pix]
clusterSize = 3

# Sampling probability of the size
samplingProb = 0.217946

# Hit X resolution in local surface frame [um]
resolutionX = 4.31227

# Hit Y resolution in local surface frame [um]
resolutionY = 4.17356

[[ClusterSizeBasedDigitizer]]
# Size of the simulated cluster [N pix]
clusterSize = 4

# Sampling probability of the size
samplingProb = 0.329402

# Hit X resolution in local surface frame [um]
resolutionX = 4.90848

# Hit Y resolution in local surface frame [um]
resolutionY = 5.09384

[TrackAngleDigitizer]
# Gaussian angle smearing resolution
# for constraint surfaces [mrad]
constraintSurfaceResolutionPhi = 1
constraintSurfaceResolutionTheta = 1

[SigConstantMultiplicityGenerator]
# Number of measurements to generate
nMeasurements = 1

[SigRootHistMultiplicityGenerator]
# Path to the hist file
filePath = """
/home/romanurmanov/work/E320/E320Prototype/\
E320Prototype_fastsim_data/multiplicity_dists/\
multiplicity-hist.root\
"""

# Hist name
histName = "multiplicity-hist"

[SigMeasurementsEmbeddingAlgorithm]
# WhiteBoard name of the input sim measurements
inputSourceLinks = "SimMeasurements"

# WhiteBoard name of the input sim clusters
inputSimClusters = "SimClusters"

# WhiteBoard name of the input sim measurement indices
inputSourceLinkIndices = "SimMeasurementIndices"

# WhiteBoard name of the output measurements
outputSourceLinks = "Measurements"

# WhiteBoard name of the output clusters
outputSimClusters = "Clusters"

# WhiteBoard name of the output measurement indices
outputSourceLinkIndices = "MeasurementIndices"

[UniformBackgroundCreator]
# Measurement resolution in local X axis
resolutionX = 5

# Measurement resolution in local Y axis
resolutionY = 5

# Number of generated measurements per surface
nMeasurementsPerSurface = 20

[BkgConstantMultiplicityGenerator]
# Number of measurements to generate
nMeasurements = 1

[BkgMeasurementsEmbeddingAlgorithm]
# WhiteBoard name of the input sim measurements
inputSourceLinks = "Measurements1"

# WhiteBoard name of the input sim clusters
inputSimClusters = "Clusters1"

# WhiteBoard name of the input sim measurement indices
inputSourceLinkIndices = "MeasurementIndices1"

# WhiteBoard name of the output measurements
outputSourceLinks = "Measurements"

# WhiteBoard name of the output clusters
outputSimClusters = "Clusters"

# WhiteBoard name of the output measurement indices
outputSourceLinkIndices = "MeasurementIndices"

# Number of measurements to generate
nMeasurements = 1

[E320RootSimClusterWriter]
# WhiteBoard name of the input clusters
inputClusters = "Clusters"

# Output tree name
treeName = "clusters"

# Output file path
filePath = """
/home/romanurmanov/work/E320/E320Prototype/\
E320Prototype_dataInRootFormat/sim/\
clusters.root\
"""

[E320MagneticFieldWriter]
# Output tree name
treeName = "magnets"

# Output file path
filePath = """
/home/romanurmanov/work/E320/E320Prototype/\
E320Prototype_dataInRootFormat/sim/\
magnets.root\
"""
